# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'Alamofire', '~> 3.1.2'
pod 'Kingfisher', '~> 1.8.1'
pod 'SnapKit', '~> 0.18.0'
pod 'ReactiveCocoa', '~> 4.0.4-alpha-1'
pod 'SVProgressHUD', '2.0-beta'
pod 'CryptoSwift', '~> 0.1.1'
pod 'AFNetworking','2.6.3'
pod 'MJRefresh', '~> 3.0.7'
pod 'APParallaxHeader'
pod 'Bugtags'
pod 'AttributedLabel'
