# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'iDoctor' do
    pod 'MKNetworkKit', '~> 0.87'
    pod 'FMDB', '~> 2.3'
    pod 'JSONKit-NoWarning', '~> 1.2'
    pod 'iRate', '~> 1.10.2'
    pod 'iVersion', '~> 1.10.6'
    pod 'HPGrowingTextView', '~> 1.1'
    pod 'THProgressView', '~> 1.0'
    pod 'MBProgressHUD', '~> 0.8'
    pod 'MWPhotoBrowser', '~> 1.4.0'
    pod 'WCAlertView', '~> 1.0.1'
    pod 'TTTAttributedLabel', '~> 1.10.1'
    pod 'Base64', '~> 1.0.1'
    pod 'iOS-QR-Code-Encoder', '~> 0.0.1'
    pod 'BMXSwitch', '~> 1.0'
    pod 'IQKeyboardManager', '~> 3.0.6'
    pod 'SlimeRefresh', '~> 0.0.1'
    pod 'UMeng', '~> 2.2.1'
    pod 'EaseMobSDK', '~> 2.1.3.3'
    pod 'UINavigationControllerWithCompletionBlock', '~> 0.0.7'
    pod 'PureLayout', '~> 2.0.6'
    pod 'REMenu', '~> 1.10'
    pod 'WEPopover', '~> 1.0.0'
    pod 'MJRefresh', '~> 2.0.1'
	pod 'UIAlertView-Blocks', '~> 1.0'
	pod 'UITextView+Placeholder', '~> 1.0.9'
   pod 'Masonry', '~> 0.6.1'
end











